name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  session:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Debug Session
        uses: csexton/debugger-action@master
